# for context, see subm.js (IOU a README)

runtime: nodejs14

instance_class: F2

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

network:
  # try to use the same instance that checked passport
  session_affinity: true

includes:
  # ack: https://stackoverflow.com/a/54055525/7963
  - env_credentials.yml

# env:
#   SUBM_SESSION_SECRET: sekretsekret

#   # Firebase
#   FIREBASE_API_KEY: sekretsekret
#   FIREBASE_AUTH_DOMAIN: DDDD.firebaseapp.com
#   FIREBASE_DATABASE_URL: https://DBDBDBDB.firebaseio.com
#   FIREBASE_PROJECT_ID: PPPPP
#   FIREBASE_APP_ID: 123...

#   # Discord
#   DISCORD_API_TOKEN: sekretsekret
#   DISCORD_GUILD_ID: 585...
#   # DISCORD_USER_ID: 358096357862408195
#   DISCORD_CLIENT_ID: 874...
#   DISCORD_CLIENT_SECRET: sekretsekret

#   # Google Cloud (Storage)
#   GOOGLE_SERVICES_EMAIL: acct@xyz.iam.gserviceaccount.com
#   GCS_STORAGE_BUCKET: my_bucket
#   GCS_PRIVATE_KEY: |
#       Bag Attributes
#       ...
#       sekretsekret
